### ISSUE TITLE
sslstrip v2 ?

### ISSUE THREAD

**Issue by vitteloil** [xdavidhu/mitmAP#14] opened 2016-12-19 12:47 UTC
Hey ;)
I didn't find in the doc (noexistent) but is the sslstrip shipped supposed to add a 'w' before all subdomains ? Because I don't see this behavior.
Also, when launching wireshark on the AP interface , when browsing https I don't see http connections, but SSL/TLS ones only.

using latest kali and packages are up to date

**Comment by xdavidhu** [comment] 2016-12-19 15:02
So SSLStrip is not running for you?

----
Also if you are going directly to the https site, sslstrip will not work. Try going to the domain name directly / and clearing cache from the browser.

**Comment by xdavidhu** [comment] 2016-12-26 21:03
Closing because of no reply from OP.

Please re-open if the issue is still relevant.

**Closed by xdavidhu** 2016-12-26 21:03 UTC
