### ISSUE TITLE
Problems on Raspberry Pi

### ISSUE THREAD

**Issue by shinobiultra** [xdavidhu/mitmAP#10] opened 2016-12-05 15:30 UTC
I've got 2 problems. I've got fully up to date RPi 3 and when i try to laung WireShark with GUI, it gives me 
`Traceback (most recent call last):
  File "mitmAP_rpi.py", line 196, in <module>
    if tshark_if == "y" or tshark_if == "":
NameError: name 'tshark_if' is not defined`
which seems easy to fix and not that bad actually as i can use TShark. 

Second problem is worse tho. When launching SSLStrip, i get : 

tail: cannot open â€/home/pi/mitmAP/logs/mitmap-sslstrip.logâ€ for reading: No such file or directory
tail: no files remaining
[!] Stopping...
No screen session found.
No screen session found.
No screen session found.
[I] Stopping DNSMASQ server...
[I] Restoring old dnsmasq.cfg...
[I] Deleting old '/etc/dnsmasq.hosts' file...
[I] Removeing speed limit from wlan0...
[I] Flushing iptables rules...
[I] Traffic have been saved to the file '/home/pi/mitmAP/logs/mitmap-sslstrip.log' and to file '/home/pi/mitmAP/logs/mitmap-tshark.pcap'.
[I] Traffic have been saved to the file '/home/pi/mitmAP/logs/mitmap-tshark.pcap'.

[!] WARNING: If you want to use the AP interface normally, please reboot the PI!

[I] mitmAP stopped.

which is kinda bad as i can't unleash full potential of your tool. Anyway i am looking forward for fixes and updates! I always like those small "indie" tools. 
Good Luck!:)

**Comment by Parasimpaticki** [comment] 2016-12-05 16:10
First problem fixed here:
https://github.com/xdavidhu/mitmAP/compare/master...Parasimpaticki:patch-3

**Comment by Parasimpaticki** [comment] 2016-12-05 16:27
Failed to recreate the second problems...

**Comment by xdavidhu** [comment] 2016-12-05 19:08
Yes thank you, I fixed the tshark_if problem.
For the sslstrip one, i don't know what caused it. It looks like there are some kind of corruption in the file location variable(?), like this: "â€�"
But if you are not able to recreate the problem, than maybe there was some kind of other issue.

**Comment by xdavidhu** [comment] 2016-12-05 19:09
Please close the issue if you are sure that you cant reproduce the problem.

**Comment by mehmetuken** [comment] 2016-12-05 20:53
> pi@raspberrypi:~/mitmAP $ sudo python3 mitmAP_rpi.py
>            _ _              ___  ______
>           (_) |            / _ \ | ___ \
>  _ __ ___  _| |_ _ __ ___ / /_\ \| |_/ /
> | '_ ` _ \| | __| '_ ` _ \|  _  ||  __/
> | | | | | | | |_| | | | | | | | || |
> |_| |_| |_|_|\__|_| |_| |_\_| |_/\_| 2.0
>       RaspberryPI version   by @xdavidhu
> 
> [?] Install/Update dependencies? Y/n: n
> [?] Please enter the name of your wireless interface (for the AP): wlan0
> [?] Please enter the name of your internet connected interface: eth0
> [I] Killing wpa_supplicant on wlan0...
> [?] Use SSLSTRIP 2.0? Y/n: y
> [?] Capture unencrypted images with DRIFTNET? (ONLY WORKS WITH GUI) y/N: n
> [I] Backing up /etc/dnsmasq.conf...
> [I] Creating new /etc/dnsmasq.conf...
> [I] Deleting old config file...
> [I] Writing config file...
> [?] Create new HOSTAPD config file at '/etc/hostapd/hostapd.conf' Y/n: y
> [?] Please enter the SSID for the AP: Free WIFI
> [?] Please enter the channel for the AP: 10
> [?] Enable WPA2 encryption? y/N: n
> [I] Deleting old config file...
> [I] Writing config file...
> [I] Configuring AP interface...
> [I] Applying iptables rules...
> [?] Set speed limit for the clients? Y/n: y
> [?] Download speed limit (in KB/s): 100
> [?] Upload speed limit (in KB/s): 100
> [I] Setting speed limit on wlan0...
> [?] Start WIRESHARK on wlan0? (ONLY WORKS WITH GUI) y/N: n
> [?] Capture packets to .pcap with TSHARK? (no gui needed) Y/n: y
> [?] Spoof DNS manually? y/N: n
> [I] Starting DNSMASQ server...
> [I] Starting AP on wlan0 in screen terminal...
> [I] Starting TSHARK...
> 
> TAIL started on /home/pi/mitmAP/logs/mitmap-sslstrip.log... Wait for output... (press 'CTRL + C' to stop)
> Only POST requests will be shown.
> 
> tail: cannot open ‘/home/pi/mitmAP/logs/mitmap-sslstrip.log’ for reading: No such file or directory
> tail: no files remaining
> 
> [!] Stopping...
> No screen session found.
> No screen session found.
> No screen session found.
> [I] Stopping DNSMASQ server...
> [I] Restoring old dnsmasq.cfg...
> [I] Deleting old '/etc/dnsmasq.hosts' file...
> [I] Removeing speed limit from wlan0...
> [I] Flushing iptables rules...
> [I] Traffic have been saved to the file '/home/pi/mitmAP/logs/mitmap-sslstrip.log' and to file '/home/pi/mitmAP/logs/mitmap-tshark.pcap'.
> [I] Traffic have been saved to the file '/home/pi/mitmAP/logs/mitmap-tshark.pcap'.
> 
> [!] WARNING: If you want to use the AP interface normally, please reboot the PI!
> 
> [I] mitmAP stopped.

Problem not reduce

**Comment by xdavidhu** [comment] 2016-12-09 19:34
Closing the issue because of no reply from the OP.

**Closed by xdavidhu** 2016-12-09 19:34 UTC

**Comment by arslan385385** [comment] 2018-02-26 08:39
sir how to uninstall mitmap on kail linux
