### ISSUE TITLE
Connectivity Issue

### ISSUE THREAD

**Issue by beeprime** [xdavidhu/mitmAP#15] opened 2017-01-06 07:23 UTC
I am using Kali Linux on-board wi-fi card as INTERNET facing card and external ALFA card as Access Point. MITMAP gives no error but simultaneously no AP is coming live.

**Comment by xdavidhu** [comment] 2017-01-06 07:36
Have you said yes to crrate the HOSTAPD config file when asked?

**Comment by noh950** [comment] 2017-01-06 19:52
same thing for me with vmware.

**Comment by xdavidhu** [comment] 2017-01-06 20:06
@noh950 Have you said yes to crrate the HOSTAPD config file when asked?

**Comment by noh950** [comment] 2017-01-06 20:06
yes

**Comment by noh950** [comment] 2017-01-06 20:08
I'm connected through NAT plus an external ralink usb

**Comment by xdavidhu** [comment] 2017-01-06 20:09
When you stop it, can you see any text about "No screen session found."?

**Comment by noh950** [comment] 2017-01-06 20:11
Stopping...
No screen session found.
and the restoring lines ...

**Comment by xdavidhu** [comment] 2017-01-06 20:19
Its caused by hostapd than. Try running it manually: sudo hostapd /etc/hostapd/hostapd.conf

**Comment by noh950** [comment] 2017-01-06 20:34
In my Kali 2016.2 Hostapd is neither installer nor in the repository.
What should I do. Install it manually ?

**Comment by xdavidhu** [comment] 2017-01-06 20:50
@noh950 I tried it before, and im sure its in the kali repos.

apt-get update
apt-get install hostapd

**Comment by noh950** [comment] 2017-01-06 20:52
Done I had to add the repository in the sources.list

**Comment by xdavidhu** [comment] 2017-01-06 20:52
So its working by the default kali install?

**Comment by crypiehef** [comment] 2017-01-06 20:54
I found it in the repo. 

Crypiehef

**Comment by noh950** [comment] 2017-01-06 21:05
I got this when trying to ren Hostapd manually 

sudo hostapd /etc/hostapd/hostapd.conf
Configuration file: /etc/hostapd/hostapd.conf
Line 10: invalid WPA passphrase length 0 (expected 8..63)
WPA-PSK enabled, but PSK or passphrase is not configured.
2 errors found in configuration file '/etc/hostapd/hostapd.conf'
Failed to set up interface with /etc/hostapd/hostapd.conf
Failed to initialize interface

**Comment by xdavidhu** [comment] 2017-01-06 21:12
Its a problem with your interface. Maybe something to do with the virtual machine.
Also make sure you select your correct wireless interface when you start mitmAP.
Check for interfaces with the "ifconfig" command.

**Comment by noh950** [comment] 2017-01-06 21:21
Yes i am going to try until I got the script work. It looks terrific. Thanks a lot for the script and for your help.

**Comment by xdavidhu** [comment] 2017-01-06 21:26
Cool! I am happy to help if you got any other problems later.

**Comment by noh950** [comment] 2017-01-06 21:52
Solved ! I think the WPA option was the cause. I disabled it.

**Comment by noh950** [comment] 2017-01-06 22:06
xdavidhu entring the passphrase is it obligatory or optional to the foctionment of the script ?

**Comment by xdavidhu** [comment] 2017-01-08 23:11
@noh950 no its not, only if you say yes to wpa2 encryption, because than you must enter a passphrase.

now i can see what was you problem! thanks, going to add blank password detection to mitmAP.

Thank you for your reply/issue report, closing this for now.

**Closed by xdavidhu** 2017-01-08 23:11 UTC
